version: '3'
services:
  web:
    build: .
    ports:
      - "6901:6901"
      - "5901:5901"
    volumes:
      - .:/./appium
    command: 
      - curl -LJO https://github.com/appium/appium-desktop/releases/download/v1.15.1/Appium-linux-1.15.1.AppImage --output appium.AppImage
      - sudo mount -o loop Some.AppImage /mnt
      - ./Appium-linux-1.15.1.AppImage
    environment:
      FLASK_ENV: development